version: 2.1


orbs:
  orb: invocations/orb@1.2.0


jobs:
  # Unit+integration tests, with coverage
  coverage:
    executor:
      name: orb/default
    steps:
      - orb/setup
      # Integration suite requires sudo, ssh
      - run: inv ci.make-sudouser
      - run: inv ci.make-sshable
      - run: sudo apt update
      - run: sudo apt install -y openssh-server wamerican-large
      - run: sudo /etc/init.d/ssh start
      - orb/sudo-coverage
      - orb/debug


workflows:
  main:
    jobs:
      - orb/lint:
          name: Lint
      - orb/format:
          name: Style check
      - coverage:
          name: Test
      - orb/test-release:
          name: Release test
      - orb/test:
          name: Test << matrix.version >>
          requires: ["Test"]
          matrix:
            parameters:
              version: ["3.7", "3.8", "3.9"]
      - orb/docs:
          name: "Docs"
          requires: ["Test"]
